-- ===============================================================
--
--   NOM du Cas       :  BDD_RENTCAR
--   NOM de SGBD      :  MySQL
--   Date de création :  MAI 2021
--   Auteur           :  HUANG Pascal LAY Frédéric QURESHI Hammad
--
-- ===============================================================
DROP DATABASE IF EXISTS rentcar;
CREATE DATABASE rentcar;
USE rentcar;

DROP TABLE IF EXISTS EMPLOYE ;
DROP TABLE IF EXISTS CHAUFFEUR ;
DROP TABLE IF EXISTS VEHICULE ;
DROP TABLE IF EXISTS CLIENT ;
DROP TABLE IF EXISTS PROGRAMME_FIDELITE ;
DROP TABLE IF EXISTS ASSURANCE ;
DROP TABLE IF EXISTS AGENCE ;
DROP TABLE IF EXISTS ADRESSE ;
DROP TABLE IF EXISTS FACTURE ;
DROP TABLE IF EXISTS REPARTIR ;
DROP TABLE IF EXISTS RESERVER ;
DROP TABLE IF EXISTS LOUER ;
DROP TABLE IF EXISTS RENDRE ;
DROP TABLE IF EXISTS SOUSCRIT ;
DROP TABLE IF EXISTS STATIONNER ;
DROP TABLE IF EXISTS HABITE_A ;

#------------------------------------------------------------
# TABLE: EMPLOYE
#------------------------------------------------------------

CREATE TABLE EMPLOYE(
   ID_EMPLOYE 		INT NOT NULL AUTO_INCREMENT,
   NOM 				VARCHAR(50) NOT NULL,
   PRENOM 			VARCHAR(50) NOT NULL,
   EMAIL 			VARCHAR(50) NOT NULL,
   NUM_TEL 			NUMERIC(10) NOT NULL,
   RUE 				VARCHAR(50) NOT NULL,
   VILLE 			VARCHAR(50) NOT NULL,
   CODE_POSTAL 		NUMERIC (5) NOT NULL,
   CONSTRAINT EMPLOYE_PK PRIMARY KEY (ID_EMPLOYE)
) ENGINE = 'InnoDB';

#------------------------------------------------------------
# TABLE: CHAUFFEUR
#------------------------------------------------------------

CREATE TABLE CHAUFFEUR(
   ID_CHAUFFEUR 	INT NOT NULL AUTO_INCREMENT,
   NOM 				VARCHAR(50) NOT NULL,
   PRENOM 			VARCHAR(50) NOT NULL,
   EMAIL 			VARCHAR(50) NOT NULL,
   NUM_TEL 			NUMERIC(10) NOT NULL,
   ID_EMPLOYE 		INT NOT NULL,
   CONSTRAINT CHAUFFEUR_PK PRIMARY KEY (ID_CHAUFFEUR),
   CONSTRAINT CHAUFFEUR_EMPLOYE_AK UNIQUE (ID_EMPLOYE),
   CONSTRAINT CHAUFFEUR_EMPLOYE_FK FOREIGN KEY (ID_EMPLOYE) REFERENCES EMPLOYE(ID_EMPLOYE)
) ENGINE = 'InnoDB';

#------------------------------------------------------------
# TABLE: VEHICULE
#------------------------------------------------------------

CREATE TABLE VEHICULE(
   MATRICULE 			VARCHAR(50) NOT NULL,
   MARQUE 				VARCHAR(50) NOT NULL,
   MODELE 				VARCHAR(50),
   KILOMETRAGE 			VARCHAR(50) NOT NULL,
   BOITE 				VARCHAR(50),
   CLIMATISATION 		BOOL NOT NULL,
   RESERVOIRE 			VARCHAR(50),
   ETAT 				VARCHAR(50),
   CATEGORIE 			ENUM ('ECONOMIQUE', 'CONFORT', 'LUXE'),
   CARBURANT 			ENUM ('GAZOLE', 'ESSENCE', 'SP95', 'GPL', 'ELECTRIQUE', 'ETHANOL'),
   TARIF_JOUR 			NUMERIC (3) NOT NULL,
   CAUTION 				NUMERIC (6) NOT NULL,
   CONSTRAINT VEHICULE_PK PRIMARY KEY (MATRICULE)
) ENGINE = 'InnoDB';

#------------------------------------------------------------
# TABLE: CLIENT
#------------------------------------------------------------

CREATE TABLE CLIENT(
   ID_CLIENT 			INT NOT NULL AUTO_INCREMENT,
   NOM 					VARCHAR(50) NOT NULL,
   PRENOM 				VARCHAR(50) NOT NULL,
   EMAIL 				VARCHAR(50) NOT NULL,
   NUM_TEL 				NUMERIC(10) NOT NULL,
   RUE 					VARCHAR(50) NOT NULL,
   VILLE 				VARCHAR(50) NOT NULL,
   CODE_POSTAL 			NUMERIC(5) NOT NULL,
   NB_LOC				NUMERIC(4) NOT NULL,
   CONSTRAINT CLIENT_PK PRIMARY KEY(ID_CLIENT)
) ENGINE = 'InnoDB';

#------------------------------------------------------------
# TABLE: PROGRAMME DE FIDELITE
#------------------------------------------------------------

CREATE TABLE PROGRAMME_FIDELITE(
   ID_FIDELITE 			INT NOT NULL AUTO_INCREMENT,
   DUREE 				NUMERIC (3) NOT NULL,
   DESCRIPTION 			ENUM ('PLATINIUM', 'GOLD', 'BRONZE'),
   PRIX 				NUMERIC (6) NOT NULL,
   TAUX_REDUC 			INT NOT NULL,
   CONSTRAINT PROGRAMME_FIDELITE_PK PRIMARY KEY(ID_FIDELITE)
) ENGINE = 'InnoDB';

#------------------------------------------------------------
# TABLE: ASSURANCE
#------------------------------------------------------------

CREATE TABLE ASSURANCE(
   ID_ASSURANCE 		INT NOT NULL AUTO_INCREMENT,
   DESCRIPTION 			VARCHAR(50),
   PRIX 				NUMERIC (6) NOT NULL,
   CONSTRAINT ASSURANCE_PK PRIMARY KEY(ID_ASSURANCE)
) ENGINE = 'InnoDB';

#------------------------------------------------------------
# TABLE: AGENCE
#------------------------------------------------------------

CREATE TABLE AGENCE(
   ID_AGENCE 			INT NOT NULL AUTO_INCREMENT,
   NOM 					VARCHAR(50) NOT NULL,
   NUM_TEL 				NUMERIC (10) NOT NULL,
   ADRESSE 				VARCHAR(250) NOT NULL,
   COORDONNEES_GPS 		VARCHAR(50) NOT NULL,
   CAPACITE				NUMERIC(2) NOT NULL,
   CONSTRAINT AGENCE_PK PRIMARY KEY(ID_AGENCE)
) ENGINE = 'InnoDB';

#------------------------------------------------------------
# TABLE: ADRESSE
#------------------------------------------------------------

#CREATE TABLE ADRESSE(
#   ID_ADRESSE 			INT NOT NULL AUTO_INCREMENT,
#   RUE 					VARCHAR(50) NOT NULL,
#   VILLE 				VARCHAR(50) NOT NULL,
#   CODE_POSTAL 			NUMERIC (5) NOT NULL,
#   CONSTRAINT ADRESSE PRIMARY KEY(ID_ADRESSE)
#) ENGINE = 'InnoDB';

#------------------------------------------------------------
# TABLE: FACTURE OU DEVIS
#------------------------------------------------------------

CREATE TABLE FACTURE(
   ID_FACTURE 			INT NOT NULL AUTO_INCREMENT,
   DUREE_LOC 			NUMERIC(3) NOT NULL,
   CONSTRAINT FACTURE_PK PRIMARY KEY(ID_FACTURE)
) ENGINE = 'InnoDB';

#CREATE TABLE REPARTIR(
#   ID_CHAUFFEUR 		INT NOT NULL AUTO_INCREMENT,
#   MATRICULE 			VARCHAR(50) NOT NULL,
#   CONSTRAINT REPARTIR_PK PRIMARY KEY(ID_CHAUFFEUR, MATRICULE),
#   CONSTRAINT REPARTIR_CHAUFFEUR_FK FOREIGN KEY(ID_CHAUFFEUR) REFERENCES CHAUFFEUR(ID_CHAUFFEUR),
#   CONSTRAINT REPARTIR_MATRICULE_FK FOREIGN KEY(MATRICULE) REFERENCES VEHICULE(MATRICULE)
#) ENGINE = 'InnoDB';

CREATE TABLE RESERVER(
   MATRICULE 			VARCHAR(50) NOT NULL,
   DATE_RESERV 			DATE,
   ID_CLIENT 			INT NOT NULL,
   CONSTRAINT RESERVER_PK PRIMARY KEY(MATRICULE),
   CONSTRAINT RESERVER_MATRICULE_FK FOREIGN KEY(MATRICULE) REFERENCES VEHICULE(MATRICULE),
   CONSTRAINT RESERVER_CLIENT_FK FOREIGN KEY(ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
) ENGINE = 'InnoDB';

CREATE TABLE LOCATION(
   MATRICULE 			VARCHAR(50) NOT NULL,
   DATE_DEBUT 			DATE,
   DATE_FIN				DATE,
   ID_CLIENT 			INT NOT NULL,
   ID_FACTURE 			INT NOT NULL,
   CONSTRAINT LOCATION_PK PRIMARY KEY(ID_CLIENT, MATRICULE, ID_FACTURE),
   CONSTRAINT LOUER_VEHICULE_FK FOREIGN KEY(MATRICULE) REFERENCES VEHICULE(MATRICULE),
   CONSTRAINT LOCATION_CLIENT_FK FOREIGN KEY(ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
   CONSTRAINT LOUER_FACTURE_FK FOREIGN KEY(ID_FACTURE) REFERENCES FACTURE(ID_FACTURE)
) ENGINE = 'InnoDB';

CREATE TABLE SOUSCRIT(
   ID_CLIENT 			INT NOT NULL,
   ID_FIDELITE 			INT NOT NULL,
   ID_ASSURANCE 		INT NOT NULL,
   DATE_SOUSCRIPTION 	DATE,
   CONSTRAINT SOUSCRIT_PK PRIMARY KEY(ID_CLIENT, ID_FIDELITE, ID_ASSURANCE),
   CONSTRAINT SOUSCRIT_CLIENT_FK FOREIGN KEY(ID_CLIENT) REFERENCES CLIENT(ID_CLIENT),
   CONSTRAINT SOUSCRIT_PROGRAMME_FIDELITE_FK FOREIGN KEY(ID_FIDELITE) REFERENCES PROGRAMME_FIDELITE(ID_FIDELITE),
   CONSTRAINT SOUSCRIT_ASSURANCE_FK FOREIGN KEY(ID_ASSURANCE) REFERENCES ASSURANCE(ID_ASSURANCE)
) ENGINE = 'InnoDB';

CREATE TABLE STATIONNER(
   MATRICULE 			VARCHAR(50) NOT NULL,
   ID_AGENCE 			INT NOT NULL,
   ID_CHAUFFEUR			INT NOT NULL,
   COORDONNEES_GPS 		VARCHAR(50),
   CONSTRAINT STATIONNER_PK PRIMARY KEY(MATRICULE, ID_AGENCE, ID_CHAUFFEUR),
   CONSTRAINT STATIONNER_VEHICULE_FK FOREIGN KEY(MATRICULE) REFERENCES VEHICULE(MATRICULE),
   CONSTRAINT STATIONNER_AGENCE_FK FOREIGN KEY(ID_AGENCE) REFERENCES AGENCE(ID_AGENCE),
   CONSTRAINT STATIONNER_CHAUFFEUR_FK FOREIGN KEY(ID_CHAUFFEUR) REFERENCES CHAUFFEUR(ID_CHAUFFEUR)
) ENGINE = 'InnoDB';

CREATE TABLE HABITE_A(
   ID_EMPLOYE 			INT NOT NULL,
   ID_CLIENT 			INT NOT NULL,
   #ID_ADRESSE 			INT NOT NULL,
   CONSTRAINT HABITE_A_PK PRIMARY KEY(ID_EMPLOYE, ID_CLIENT), #ID_ADRESSE),
   CONSTRAINT HABITE_A_EMPLOYE_FK FOREIGN KEY(ID_EMPLOYE) REFERENCES EMPLOYE(ID_EMPLOYE),
   CONSTRAINT HABITE_A_CLIENT_FK FOREIGN KEY(ID_CLIENT) REFERENCES CLIENT(ID_CLIENT)
   #CONSTRAINT HABITE_A_ADRESSE_FK FOREIGN KEY(ID_ADRESSE) REFERENCES ADRESSE(ID_ADRESSE)
) ENGINE = 'InnoDB';

COMMIT;

SELECT * FROM EMPLOYE ;
SELECT * FROM CHAUFFEUR ;
SELECT * FROM VEHICULE ;
SELECT * FROM CLIENT ;
SELECT * FROM AGENCE ;
SELECT * FROM FACTURE ;

 

